[project]
name = "Pasid-Validator-Python"
version = "0.1.0"
description = "Python version to Pasid Validator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.26.0",
    "ollama>=0.4.8",
    "python-decouple>=3.8",
]
